In [2]:
from scipy.io import loadmat
import pandas as pd
import altair as alt
import numpy as np
alt.data_transformers.enable('data_server')

DataTransformerRegistry.enable('data_server')

In [4]:
gl_10 = loadmat('../data/raw/gl_10.mat')

In [5]:
gl_10

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Nov 19 19:29:51 2020',
 '__version__': '1.0',
 '__globals__': [],
 'MUPulses': array([[array([[ 92900,  93164,  93402,  93617,  93774,  94013,  94203,  94402,
                  94625,  94812,  94990,  95223,  95418,  95604,  95815,  96040,
                  96268,  96476,  96761,  97012,  97253,  97463,  97689,  97941,
                  98146,  98345,  98622,  98849,  99191,  99504,  99759,  99937,
                 100097, 100292, 100464, 100629, 100825, 100982, 101162, 101320,
                 101488, 101660, 101842, 102016, 102214, 102373, 102479, 102540,
                 102845, 103045, 103249, 103498, 103715, 103909, 104139, 104382,
                 104603, 104804, 105002, 105192, 105388, 105582, 105771, 105977,
                 106200, 106367, 106559, 106781, 107007, 107183, 107369, 107583,
                 107794, 107989, 108303, 108511, 108729, 108984, 109196, 109418,
                 109653, 109857, 110041

In [10]:
gl_10.keys()

dict_keys(['__header__', '__version__', '__globals__', 'MUPulses', 'MUIDs', 'Cost', 'PNR', 'SIG', 'IPTs', 'fsamp', 'startSIGInt', 'stopSIGInt', 'ref_signal', 'origRecMode', 'SIGFilePath', 'SIGFileName', 'DecompRuns', 'IED', 'discardChannelsVec', 'description', 'SIGlength', 'ProcTime', 'DecompStat'])

In [46]:
gl_10["fsamp"]

array([[2048]], dtype=uint16)

In [12]:
gl_10["SIG"].shape

(13, 5)

In [20]:
gl_10["SIG"][0][1].shape

(1, 215473)

In [47]:
signal = pd.DataFrame(gl_10["SIG"][0][1]).T

In [48]:
signal = signal.reset_index().rename(columns={"index": "time", 0:"emg"})

In [52]:
signal["time"] = signal["time"] / 2048

In [53]:
signal

time        emg
0         0.000000  46.793620
1         0.000488  13.224284
2         0.000977  -7.120768
3         0.001465   0.000000
4         0.001953   6.103516
...            ...        ...
215468  105.208984   6.103516
215469  105.209473  16.276042
215470  105.209961  26.448568
215471  105.210449  50.862630
215472  105.210938  36.621094

[215473 rows x 2 columns]

In [105]:
alt.Chart(signal, title="Raw EMG data from single channel").encode(
    x=alt.X("time", title="Time (s)", scale=alt.Scale(nice=False)),
    y=alt.Y("emg", title="Voltage", axis=alt.Axis(labels=False, ticks=False)),
).mark_line(strokeWidth=0.2).configure_axis(
    grid=False, labelFontSize=14, titleFontSize=20
).configure_view(strokeOpacity=0).configure_title(fontSize=20)

alt.Chart(...)

# hmmmmmmmmmmmm muscles hmmmmmmm

In [70]:
zoom_in = signal.loc[signal.loc[:, "time"] < 37]

In [71]:
alt.Chart(zoom_in).encode(
    x=alt.X("time", title="Time (s)"), y=alt.Y("emg", title=None)
).mark_line().configure_axis(grid=False, labelFontSize=14, titleFontSize=20)

alt.Chart(...)

In [124]:
np.array(gl_10["SIG"])

(13, 5)

In [112]:
sig_array = gl_10["SIG"].flatten()

In [116]:
sig_array.shape

(65,)

In [121]:
np.delete(sig_array, [], axis=0)

array([array([], shape=(0, 0), dtype=uint8),
       array([[46.79361979, 13.22428385, -7.12076823, ..., 26.44856771,
               50.86263021, 36.62109375]])                             ,
       array([[76.29394531, 39.67285156, 29.50032552, ..., 34.58658854,
               47.8108724 , 57.98339844]])                             ,
       array([[74.2594401 ,  4.06901042, -5.08626302, ..., 21.36230469,
               30.51757812, 36.62109375]])                             ,
       array([[62.05240885, 28.48307292, 17.29329427, ...,  3.05175781,
               22.37955729, -5.08626302]])                             ,
       array([[80.36295573, 17.29329427, 21.36230469, ..., 29.50032552,
               34.58658854, 53.91438802]])                             ,
       array([[ -11.18977865,  104.77701823, -128.17382812, ...,   46.79361979,
                 49.8453776 ,   68.15592448]])                                 ,
       array([[45.77636719, 15.25878906, -1.0172526 , ..., 33.5693359